service: cloudflare-bypass

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  memorySize: 256
  region: eu-central-1
  versionFunctions: false

plugins:
  - serverless-python-requirements

functions:
  proxy:
    handler: handler.proxy