service: movies-telegram-bot

custom:
  tableName: 'infoTable'
  playerUrl: 'https://movies-player.web.app/'

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["InfoTable", "Arn" ] }

functions:
  search:
    handler: handlers/search.handler
    events:
      - http: 
          path: api/trackers/{provider}/search
          method: get
          cors: true
          request:
            parameters:
              path:
                provider: true
              querystrings:
                q: true

  provider:
    handler: handlers/provider.handler
    events:
      - http: 
          path: api/trackers
          method: get
          cors: true

  info:
    handler: handlers/info.handler
    timeout: 12
    events:
      - http: 
          path: api/trackers/{provider}/items/{resultId}
          method: get
          cors: true
          request:
            parameters:
              path:
                - provider: true 
                - resultId: true 
    environment:
      TABLE_NAME: ${self:custom.tableName}

  extract:
    handler: handlers/extract.handler
    events:
      - http: 
          path: api/extract
          method: get
          cors: true

  bot:
    handler: handlers/bot.handler
    events:
      - http: 
          path: bot
          method: any
          cors: true
    environment:
      TOKEN: ${ssm:bot_ru_TOKEN}
      PLAYER_URL: ${self:custom.playerUrl}
      PROVIDER: 'videocdn,7serealov,seasonvar,animevost,kinogo'
      INLINE_PROVIDERS: 'videocdn,7serealov,seasonvar,animevost,kinogo'

  uabot:
    handler: handlers/bot.handler
    events:
      - http: 
          path: bot/ua
          method: any
          cors: true
    environment:
      TOKEN: ${ssm:bot_ua_TOKEN}
      PLAYER_URL: ${self:custom.playerUrl}
      PROVIDER: 'kinoukr,uaserials'
      INLINE_PROVIDERS: 'kinoukr,uaserials'

  # vumoobot:
  #   handler: handlers/bot.handler
  #   events:
  #     - http: 
  #         path: bot/vumoo
  #         method: any
  #         cors: true
  #   environment:
  #     TOKEN: ${ssm:bot_vumoo_TOKEN}
  #     PLAYER_URL: ${self:custom.playerUrl}
  #     PROVIDER: 'vumoo'
  #     INLINE_PROVIDERS: 'vumoo'

resources:
  Resources:
    InfoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: TRUE