service: movies-telegram-bot

custom:
  cacheTable: cache-${opt:stage, 'dev'}
  playerUrl: 'https://movies-player.firebaseapp.com/#/watch'
  mongoUrl: 'mongodb+srv://lambda:${ssm:MONGODB_PASSWORD}@moviescachecluster-mex1w.mongodb.net/test'
  analyticsTable: analyticsTable-${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  versionFunctions: false
  memorySize: 512
  environment:
    ANALYTIC_TABLE: ${self:custom.analyticsTable}
    CACHE_TABLE: ${self:custom.cacheTable}
    MONGODB_URI: ${self:custom.mongoUrl}
    ANALYTIC_RETENTION: 90
    ANALYTIC_TIMEZONE: 'Europe/Kiev'
    STAGE: ${opt:stage, 'dev'}
    CACHE_TTL: 1800
    FILMS_PROVIDERS: 'videocdn,kinovod,kinogo,seasonvar'
    ANIME_PROVIDERS: 'animevost,anidub,animedia'
    PLAYER_URL: ${self:custom.playerUrl}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.analyticsTable}"
    - Effect: Allow
      Action:
        - logs:PutLogEvents
        - logs:DescribeLogStreams
      Resource: "arn:aws:logs:${self:provider.region}:*:log-group:web-${opt:stage, 'dev'}:log-stream:*"

functions:
  library:
    handler: handlers/library.handler
    events:
      - http: 
          path: api/library
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                q: true
                type: true

  search:
    handler: handlers/search.handler
    timeout: 12
    events:
      - http: 
          path: api/trackers/{provider}/search
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                q: true

  source:
    handler: handlers/source.handler
    events:
      - http: 
          path: api/trackers/{provider}/items/{resultId}/source/{sourceId}
          method: get
          cors: true

  provider:
    handler: handlers/provider.handler
    events:
      - http: 
          path: api/trackers
          method: get
          cors: true

  info:
    handler: handlers/info.handler
    timeout: 30
    events:
      - http: 
          path: api/trackers/{provider}/items/{resultId}
          method: get
          cors: true

  extract:
    handler: handlers/extract.handler
    events:
      - http: 
          path: api/extract
          method: get
          cors: true

  bot:
    handler: handlers/bot.handler
    timeout: 12
    events:
      - http: 
          path: bot
          method: any
          cors: true
    environment:
      BOT_TYPE: 'films'
      TOKEN: ${ssm:bot_ru_TOKEN_${opt:stage, 'dev'}}

  animebot:
    handler: handlers/bot.handler
    events:
      - http: 
          path: bot/anime
          method: any
          cors: true
    environment:
      BOT_TYPE: 'anime'
      LOCALIZATION_TYPE: 'localization/anime'
      TOKEN: ${ssm:bot_anime_TOKEN_${opt:stage, 'dev'}}
  
  logger:
    handler: handlers/logger.handler
    events:
      - http: 
          path: api/log
          method: post
          cors: true
    environment:
      ALLOWED_DOMAINS: 'localhost:3000,movie-player.surge.sh,movies-player.firebaseapp.com,movies-player.web.app'
      LOG_GROUP: web-${opt:stage, 'dev'}

package:
  exclude:
   - test/**

resources:
  Resources:
    analyticsTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:custom.analyticsTable}
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: "N"
          - AttributeName: date
            AttributeType: S
          - AttributeName: month
            AttributeType: S
          - AttributeName: time
            AttributeType: "N"
        KeySchema:
          - AttributeName: date
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: userIdx
            KeySchema:
              - AttributeName: uid
                KeyType: HASH
              - AttributeName: time
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: monthIdx
            KeySchema:
              - AttributeName: month
                KeyType: HASH
              - AttributeName: time
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true