service: movies-telegram-bot

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1

functions:
  search:
    handler: index.search
    events:
      - http: 
          path: api/trackers/{provider}/search
          method: get
          cors: true
          request:
            parameters:
              path:
                provider: true
              querystrings:
                q: true

  provider:
    handler: index.provider
    events:
      - http: 
          path: api/trackers
          method: get
          cors: true

  info:
    handler: index.info
    events:
      - http: 
          path: api/trackers/{provider}/items/{resultId}
          method: get
          cors: true
          request:
            parameters:
              path:
                - provider: true 
                - resultId: true 

  extract:
    handler: index.extract
    events:
      - http: 
          path: extract
          method: get
          cors: true

  bot:
    handler: index.bot
    events:
      - http: 
          path: bot
          method: any
          cors: true